services:
  leam:
    build: .
    ports:
      - "5000:5000"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./data:/app/data
      - ./modules:/app/modules
      - ./bg_videos:/app/bg_videos
      - ./secrets:/app/secrets
      - ./static:/app/static
      - ./templates:/app/templates
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '1.0'
          memory: 2G
