version: '3.8'

services:
  leam:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./modules:/app/modules
      - ./bg_videos:/app/bg_videos
      - ./secrets:/app/secrets
      - ./static:/app/static
      - ./templates:/app/templates
    env_file:
      - .env
    restart: always
